### ISSUE TITLE
Improve lookup on /practice and /ccg pages

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#46] opened 2016-05-26 12:01 UTC
We only have a simple text lookup, which is not the best user experience. Also, the implementation of the /practice page is poor.

A map on the CCG page would a straightforward improvement. 

Simple fix for practice page: use ajax + existing API methods so page is less slow. 

Harder fix for practice page: postcode lookup.

Possibly they should be aggregated.

**Comment by frabcus** [comment] 2017-02-06 13:21
I couldn't find my GP (https://openprescribing.net/practice/N82082/) because I know it as St James Health Centre, but it is officially Dr Prasad's Practice. If the search also searched addresses that would have covered it. Or, is there a secondary name field for practices - it looks that way e.g. from http://www.cqc.org.uk/provider/1-199778607

**Comment by frabcus** [comment] 2017-02-06 13:23
There is some level of postcode lookup now - it searches the postcode field in the address of the practices. It isn't clear you can do this. Also it probably isn't the expected behaviour for postcode lookup, as people will often have a different postcode to their practice.

**Comment by frabcus** [comment] 2017-02-06 15:08
Can close this, as it is improved now (e.g. with basic postcode lookup) and @sebbacon rightly points out that the main audience for the website is health professionals rather than general public, so there's not much need to optimise for stuff like finding a practice (most practices know their NHS practice code for example). (I don't have closing power)

**Closed** 2017-02-06 15:19 UTC
