### ISSUE TITLE
Another nondeterminstic bigquery failure

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#646] opened 2017-11-16 14:18 UTC
```
======================================================================
ERROR: test_existing_files_deleted (frontend.tests.commands.test_create_views.CommandsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/commands/test_create_views.py", line 101, in test_existing_files_deleted
    call_command('create_views', dataset='test_hscic')
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/code/openprescribing/frontend/management/commands/create_views.py", line 61, in handle
    self.fill_views()
  File "/code/openprescribing/frontend/management/commands/create_views.py", line 96, in fill_views
    self.download_and_import(table)
  File "/code/openprescribing/frontend/management/commands/create_views.py", line 118, in download_and_import
    cursor.copy_expert(copy_sql, f)
ProgrammingError: syntax error at or near ")"
LINE 1: COPY vw__presentation_summary_by_ccg() FROM STDIN WITH (FORM...
```

**Comment by inglesp** [comment] 2017-11-16 15:30
It'd be helpful to have a link to the the Travis build, as that has a link to the PR and the git checkout.

**Comment by sebbacon** [comment] 2017-11-16 17:18
Problem is, to check it was nondeterministic I restarted the job, which wipes the history!

Next time I see this I'll preserve it...

**Comment by inglesp** [comment] 2017-12-05 15:44
I've accidentally reproduced this.

```
======================================================================
ERROR: test_import_create_views (frontend.tests.commands.test_create_views.CommandsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/inglesp/work/ebmdatalab/openprescribing/openprescribing/frontend/tests/commands/test_create_views.py", line 111, in test_import_create_views
    call_command('create_views')
  File "/Users/inglesp/.pyenv/versions/openprescribing/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/Users/inglesp/.pyenv/versions/openprescribing/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/inglesp/work/ebmdatalab/openprescribing/openprescribing/frontend/management/commands/create_views.py", line 60, in handle
    self.fill_views()
  File "/Users/inglesp/work/ebmdatalab/openprescribing/openprescribing/frontend/management/commands/create_views.py", line 92, in fill_views
    self.download_and_import(table)
  File "/Users/inglesp/work/ebmdatalab/openprescribing/openprescribing/frontend/management/commands/create_views.py", line 114, in download_and_import
    cursor.copy_expert(copy_sql, f)
ProgrammingError: syntax error at or near ")"
LINE 1: COPY vw__ccgstatistics() FROM STDIN WITH (FORMAT CSV)
                               ^
```

The syntax error must be because the downloaded file containing the exported table is empty...

...and yes, the `vw__ccgstatistics` table doesn't exist in BQ.

We need the `vw__ccgstatistics` to exist during the second half of `create_views` (ie, in the `download_and_import` stage), and it should have been created during the first half (in the `query_and_export` stage).

The reason `vw__ccgstatistics` doesn't exist is because it's created in a subprocess, and there's an error in the function in the subprocess in the code I'm testing.  The error of course gets swallowed.

So could the error we've seen on Travis have been caused by an error in the subprocess?

**Comment by inglesp** [comment] 2018-01-23 11:20
Closing this, as we haven't seen it since we started using a new dataset for each test run.

**Closed by inglesp** 2018-01-23 11:20 UTC
