### ISSUE TITLE
Date cut-off issues

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#814] opened 2018-03-21 09:44 UTC
Analyse page: [practices](https://openprescribing.net/analyse/#org=practice&orgIds=99P&numIds=0703021Q0BB&denom=nothing&selectedTab=chart) start at Feb 13 (as they should) but with no data for first 2 months. [CCGs](https://openprescribing.net/analyse/#org=CCG&orgIds=99P&numIds=0703021Q0BB&denom=nothing&selectedTab=chart) start at Aug 13. 

Dashboards: for practices, standard measures go back to May 2012 (though the low-priority measures are OK).

**Comment by inglesp** [comment] 2018-03-21 12:37
Notes so far (am currently stymied by server being offline)

Practices analyse page makes requests for:

* https://openprescribing.net/api/1.0/spending_by_practice/?format=json&code=0703021Q0BB&org=99P
  * This returns no data from 2013_02 or 2013_03, but does for remaining 58 months up to 2018_01
* https://openprescribing.net/api/1.0/org_details/?format=json&org_type=practice&keys=nothing&org=99P
  * This returns data for all 60 months up to 2018_01

The `spending_by_practice` endpoint queries `frontend_prescription`, and it looks like we're missing some (but not all) data from 2013_02 and 2013_03:

```
# select min(processing_date) from frontend_prescription where pct_id = '99P';
┌────────────┐
│    min     │
├────────────┤
│ 2013-04-01 │
└────────────┘
```

but:

```
select min(processing_date) from frontend_prescription;
┌────────────┐
│    min     │
├────────────┤
│ 2013-02-01 │
└────────────┘
```

**Comment by inglesp** [comment] 2018-03-21 17:42
In BigQuery, we don't have any data older than 2013_04 for CCG 99P:

```
SELECT
  min(month)
FROM
  hscic.prescribing
WHERE
  pct = '99P'
~~~
2013-04-01 00:00:00.000 UTC
```

And yes: this CCG was formed in April 2013:

```
>>> PCT.objects.get(pk='99P').open_date
datetime.date(2013, 4, 1)
```

So nothing to worry about here.  (There may be a separate issue about how we communicate CCG opening/closing on the analyse page.)

**Comment by inglesp** [comment] 2018-03-22 09:51
The CCG page makes requests to:

* https://openprescribing.net/api/1.0/spending_by_ccg/?format=json&code=0703021Q0BB
* https://openprescribing.net/api/1.0/org_details/?format=json&org_type=ccg&keys=nothing

Both these endpoints return data for all 60 months from 2013_02 to 2018_01.

So is the JS deciding only to show 55 months?

**Comment by sebbacon** [comment] 2018-03-22 11:13
Notes from me:

* There shouldn't be any data before a certain date in 2013 for *any* CCGs (they were all created in 2013)
so that is expected behaviour (see e.g. [here](https://github.com/ebmdatalab/openprescribing/blob/5d3ad7c0b3463b8e175d08d4d39fd4ff1d9d879f/openprescribing/media/js/src/chart_utils.js#L272), though I can't remember why CCGs were created in April but no data expected til August, according to that code...)
* Although CCGs were only formed in April, the practices existed before that, so we should still expect data for the first two months in, say, [this chart](https://openprescribing.net/analyse/#org=practice&orgIds=P83009&numIds=0703021Q0BB&denom=nothing&selectedTab=chart) 
* On the CCG page linked to in the issue, I can see data for 60 months as expected, so don't understand your reference to 55 months?

**Comment by inglesp** [comment] 2018-04-10 11:11
> There shouldn't be any data before a certain date in 2013 for any CCGs (they were all created in 2013) so that is expected behaviour

Yes, all data in `frontend_prescribing` with `processing_date < '2013-04-01'` are for PCTs.

> see e.g. [here](https://github.com/ebmdatalab/openprescribing/blob/5d3ad7c0b3463b8e175d08d4d39fd4ff1d9d879f/openprescribing/media/js/src/chart_utils.js#L272), though I can't remember why CCGs were created in April but no data expected til August, according to that code...

When we discussed this on the train, @sebbacon wasn't sure whether August 2013 was doing in the code, and whether it was a mistake (and that we'd meant April 2013).  Seb, should I change August to April?

> Although CCGs were only formed in April, the practices existed before that, so we should still expect data for the first two months in, say, [this chart](https://openprescribing.net/analyse/#org=practice&orgIds=P83009&numIds=0703021Q0BB&denom=nothing&selectedTab=chart).

There's no data before April in that chart.  Presumably this is because the CCG has no data from before April.  This is a bug -- we should be able to show a practice's data from its old PCT or CCG, and I'll try to make sure it's fixed as part of #739.

> On the CCG page linked to in the issue, I can see data for 60 months as expected, so don't understand your reference to 55 months?

In [this chart](https://openprescribing.net/analyse/#org=CCG&orgIds=99P&numIds=0703021Q0BB&denom=nothing&selectedTab=chart), data begins at 2013_08 and ends at 2018_01, which is 55 months.

**Comment by alexwalkercebm** [comment] 2018-06-27 14:01
This is a bit more of a big deal now, as with the merged practices, the data doesn't go back before May 2013, but the rest of the deciles do, making it more obvious:
![image](https://user-images.githubusercontent.com/24895935/41978949-c768bdde-7a1a-11e8-8da3-668881ca01e7.png)
https://openprescribing.net/ccg/14Y/

**Comment by inglesp** [comment] 2018-06-28 09:01
This is a new problem, and I've opened #907 to discuss.

**Comment by inglesp** [comment] 2018-07-04 11:36
I think the only outstanding problem discussed here is that analyse queries that highlight a CCG or CCGs only show data going back to August 2013, while all other queries (now) show data going back five years.

I've created #920 to track this.

**Closed by inglesp** 2018-07-04 11:36 UTC
