### ISSUE TITLE
September data import apparently duplicated August

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#644] opened 2017-11-16 11:42 UTC
So far we've established:

* The raw and converted data is correct
* The prescribing table in postgres is correct
* The Sept data in the main bigquery prescribing table is a duplicate of Aug data
* As a result, all the measures and views in postgres (generated from bigquery) have duplicates

The error is presumably in `convert_hscic_prescribing`.

**Comment by sebbacon** [comment] 2017-11-16 11:43
To clean up the incorrect data as viewed on the website, I'm doing the following:

```sql
delete from vw__ccgstatistics where date = '2017-11-01';
delete from vw__chemical_summary_by_ccg where processing_date = '2017-11-01';
delete from vw__practice_summary where processing_date = '2017-11-01';
delete from vw__presentation_summary where processing_date = '2017-11-01';
delete from vw__chemical_summary_by_practice where processing_date = '2017-11-01';
drop table prescribing_201709
```

**Comment by inglesp** [comment] 2017-11-16 14:43
The import ran with the code at b66a6e872a8afe4f0142b1a44561f915781a2c47.

`convert_hscic_prescribing` was run between 20:22 and 20:26 on 2017-11-15.

Here's what`convert_hscic_prescribing` does:

* Creates a BQ table (`tmp_eu.temp_raw_nhs_digital_data`) whose data is read from `gs://ebmdatalab/hscic/prescribing/2017_09/20171115_1510735567868_Detailed_Prescribing_Information.csv`
  * This blob exists in storage
  * However, `tmp_eu.temp_raw_nhs_digital_data` now references `gs://ebmdatalab/test_hscic/prescribing/sample.csv`, which is an artefact of test_convert_hscic_prescribing.py
    * There were no tests being run on Travis when the pipeline was running `convert_hscic_prescribing`, so I think this is unrelated (but argh!)
* `tmp_eu.temp_raw_nhs_digital_data` is queried, and the results are appended to `ebmdatalab:hscic.prescribing`
   * `ebmdatalab:hscic.prescribing` has duplicate data for 2017_08 and 2017_09
* `tmp_eu.temp_raw_nhs_digital_data` is queried again, and the results are written to `tmp_eu.formatted_prescribing_2017_09_01`
  * `tmp_eu.formatted_prescribing_2017_09_01` is identicatal to `tmp_eu.formatted_prescribing_2017_08_01`
* `tmp_eu.formatted_prescribing_2017_09_01` is exported to `gs://ebmdatalab/hscic/prescribing/2017_09/20171115_1510735567868_Detailed_Prescribing_Information.csv_formatted-*.csv.gz`
* The CSV files in storage are downloaded reassembled at `~/openprescribing-data/data/prescribing2017_09/20171115_1510735567868_Detailed_Prescribing_Information_formatted.CSV`

But what's odd is that the 2017_08 and 2017_09 `XXX_Detailed_Prescribing_Information_formatted.CSV` files differ!

**Comment by inglesp** [comment] 2017-11-17 15:07
I've just run:

```
MeasureValue.objects.filter(month='2017-09-01').delete()
MeasureGlobal.objects.filter(month='2017-09-01').delete()
ImportLog.objects.latest_in_category('prescribing').delete()
```

and cleared the Cloudflare cache, whic

**Comment by sebbacon** [comment] 2017-11-20 09:01
And I just remembered the following too:

```sql
delete from frontend_importlog where current_at = '2017-09-01' and category = 'ppu';
delete from frontend_importlog where current_at = '2017-09-01' and category = 'patient_list_size'; -- not strictly necessary
delete from frontend_ppusaving where date = '2017-09-01';
```

**Comment by inglesp** [comment] 2017-11-21 09:32
The problem was caused by us not changing the source of the `tmp_eu.temp_raw_nhs_digital_data` table.  [Here](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/convert_hscic_prescribing.py#L188-L192)'s the culprit in the code, and [here](https://github.com/ebmdatalab/openprescribing/blob/949fcfe9f836a1892a44b8286a8155fc23817a38/openprescribing/frontend/management/commands/convert_hscic_prescribing.py#L254-L257)'s how it worked pre-refactor -- note the explicit deletion of the table before recreating it.

This is fixed in #647.

**Comment by inglesp** [comment] 2017-11-21 10:55
### Clearing up

Here are the tasks that are downstream of `convert_hscic_prescribing`.

```
task_names = [
    'convert_hscic_prescribing',
    'import_hscic_prescribing',
    'backup_prescribing',
    'upload_to_bigquery',
    'import_measures',
    'generate_ppu',
    'refresh_views',
    'update_smoketests',
    'run_smoketests',
]
```

We'll have to undo each of those.

#### `convert_hscic_prescribing`

On BQ, we're going to have to:
 * delete `tmp_eu.temp_raw_nhs_digital_data`
 * delete `tmp_eu.formatted_prescribing_2017_09_01`
 * run `DELETE FROM hscic.prescribing WHERE month = TIMESTAMP('2017-09-01')`

And on storage:
 * delete `gs://ebmdatalab/hscic/prescribing/2017_09/20171115_1510735567868_Detailed_Prescribing_Information.csv_formatted-*.csv.gz`

And on the filesystem:
 * delete `~/openprescribing-data/data/prescribing2017_09/20171115_1510735567868_Detailed_Prescribing_Information_formatted.CSV`

#### `import_hscic_prescribing`

In the database:
* ~~run `DROP TABLE IF EXISTS frontend_prescription_2017_09`~~ (already done)

#### `backup_prescribing`

On storage:
* delete `gs://ebmdatalab/prescribing/prescribing_backups/2017_09*`

#### `upload_to_bigquery`

Nothing required.

#### `import_measures`

In the database:
* ~~run `MeasureValue.objects.filter(month='2017-09-01').delete()`~~
* ~~run `MeasureGlobal.objects.filter(month='2017-09-01').delete()`~~
* ~~run `ImportLog.objects.latest_in_category('prescribing').delete()`~~

#### `generate_ppu`

In the database:
* `delete from frontend_importlog where current_at = '2017-09-01' and category = 'ppu';`
* `delete from frontend_ppusaving where date = '2017-09-01';`

#### `refresh_views`

In the database:
* ~~run `delete from vw__ccgstatistics where date = '2017-09-01';`~~
* ~~run `delete from vw__chemical_summary_by_ccg where processing_date = '2017-09-01';`~~
* ~~run `delete from vw__practice_summary where processing_date = '2017-09-01';`~~
* ~~run `delete from vw__presentation_summary where processing_date = '2017-09-01';`~~
* ~~run `delete from vw__chemical_summary_by_practice where processing_date = '2017-09-01';`~~
* `delete from vw__presentation_summary_by_ccg where processing_date = '2017-09-01'`

#### `update_smoketests`

Nothing required.

#### `run_smoketests`

Nothing required.

#### The pipeline runner

Finally, we'll have to clear out the `TaskLog`s:

 * run `TaskLog.objects.filter(year=2017, month=9, task_name__in=task_names).delete()`, where:

**Comment by inglesp** [comment] 2017-11-21 14:51
Should also have removed

```
    {
      "imported_file": "/home/hello/openprescribing-data/data/prescribing/2017_09/20171115_1510735567868_Detailed_Prescribing_Information.csv",
      "imported_at": "2017-11-15T20:26:24"
    },
    {
      "imported_file": "/home/hello/openprescribing-data/data/prescribing/2017_09/20171115_1510735567868_Detailed_Prescribing_Information_formatted.CSV",
      "imported_at": "2017-11-15T21:29:36"
    }
```

from log.json.

**Comment by sebbacon** [comment] 2017-11-30 14:21
@inglesp this can be closed now, yes?

**Comment by inglesp** [comment] 2017-11-30 22:24
Yep, closing.

**Closed by inglesp** 2017-11-30 22:24 UTC
